article_home:
    path:        /{page}
    defaults:    { _controller: ArticleBundle:Article:index, page: 1 }
    requirements:
        id: \d*
    
article_voir:
    path:        /article/{id}
    defaults:    { _controller: ArticleBundle:Article:voir }
    requirements:
        id: \d+
    
article_ajout:
    path:        /add
    defaults:    { _controller: ArticleBundle:Article:ajout }
    
article_modifie:
    path:        /modifie/{id}
    defaults:    { _controller: ArticleBundle:Article:modifie }
    requirements:
        id: \d+

article_supprime:
    path:        /del
    defaults:    { _controller: ArticleBundle:Article:supprime }
    requirements:
        id: \d+
    
article_view_all:
    path:        /articles
    defaults:    { _controller: ArticleBundle:Article:view_all }
